---
- name: Template Airflow worker service file
  template:
    src: airflow-worker-edge.service.j2
    dest: /usr/lib/systemd/system/airflow-worker.service

- name: Change default beeline
  become: yes
  become_user: root
  shell: mv {{ airflow_install_dir }}/bin/beeline{,.airflow.bkp}
  ignore_errors: true