# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop airflow worker service
  ansible.builtin.systemd:
    name: airflow-worker
    state: stopped
    enabled: "{{ airflow_start_on_boot }}"

- name: Stop airflow kerberos service
  ansible.builtin.systemd:
    name: airflow-kerberos
    state: stopped
    enabled: "{{ airflow_start_on_boot }}"
