# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure configuration directory
  ansible.builtin.file:
    path: "{{ livy_jmx_exporter_conf_dir }}"
    state: directory
    owner: "{{ livy_user }}"
    group: "{{ hadoop_group }}"
    mode: "750"

- name: Render jmx-exporter config file
  ansible.builtin.copy:
    content: "{{ jmx_exporter | to_nice_yaml }}"
    dest: "{{ livy_jmx_exporter_conf_dir }}/{{ livy_jmx_exporter_conf_file }}"
    owner: "{{ livy_user }}"
    group: "{{ hadoop_group }}"
    mode: "600"
