---
- name: Template Airflow worker service file
  ansible.builtin.template:
    src: airflow-worker.service.j2
    dest: /usr/lib/systemd/system/airflow-worker.service

- name: Template Airflow flower service file
  ansible.builtin.template:
    src: airflow-flower.service.j2
    dest: /usr/lib/systemd/system/airflow-flower.service

- name: Set Redis bind address
  lineinfile:
    path: /etc/redis.conf
    regexp: '^bind'
    line: 'bind {{ redis_bind_address }}'
