---
- name: Ensure common airflow installation tasks are performed
  import_role:
    name: tosit.tdp_extra.airflow.common
    tasks_from: install

- name: Install Redis
  yum:
    name: redis
    state: present

- name: Pip install redis
  pip:
    name: "redis"
    executable: pip3
    extra_args: --constraint /tmp/constraints-3.6.txt

# - name: Start Redis service
#   systemd:
#     name: redis
#     state: started
#     enabled: yes

