---
- name: Restart redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart airflow flower service
  ansible.builtin.systemd:
    name: airflow-flower
    state: restarted
    enabled: true
    daemon_reload: true