# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop redis service
  ansible.builtin.systemd:
    name: redis
    state: stopped
    enabled: true
    daemon_reload: true

- name: stop airflow flower service
  ansible.builtin.systemd:
    name: airflow-flower
    state: stopped
    enabled: true
    daemon_reload: true
