# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart airflow scheduler service
  ansible.builtin.systemd:
    name: airflow-scheduler
    state: restarted
    enabled: "{{ airflow_start_on_boot }}"

