---
- name: Template airflow_local_settings.py file
  template:
    src: airflow_local_settings.py.j2
    dest: "{{ airflow_conf_dir }}/airflow_local_settings.py"
  
- name: Airflow Database Init
  shell: "{{ airflow_executable }} db init"

- name: Template Airflow webserver service file
  template:
    src: airflow-webserver.service.j2
    dest: /usr/lib/systemd/system/airflow-webserver.service

- name: Airflow | Delete connections
  command: "{{ airflow_executable }} connections delete {{ item.conn_id }}"
  with_items: "{{ airflow_connections }}"
  when: airflow_connections_reset
  ignore_errors: true

- name: Airflow | Add connections
  shell: >
    "{{ airflow_executable }}" connections add {{ item.conn_id }}
    {%- for key, value in item.items() if key != 'conn_id' %}
    --{{ key }} {{ value }}
    {%- endfor %}
  with_items: "{{ airflow_connections }}"
  ignore_errors: true

- name: Template Airflow flower service file
  template:
    src: airflow-flower.service.j2
    dest: /usr/lib/systemd/system/airflow-flower.service
