# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: restart airflow webserver service
  ansible.builtin.systemd:
    name: airflow-webserver
    state: restarted
    enabled: "{{ airflow_start_on_boot }}"
