# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Upload {{ ranger_kafka_dist_file }}
  ansible.builtin.copy:
    src: "{{ binaries_local_dir }}/{{ ranger_kafka_dist_file }}"
    dest: "{{ binaries_upload_dir }}"
    owner: root
    group: root
    mode: "644"
  diff: no

- name: Extract {{ ranger_kafka_dist_file }}
  ansible.builtin.unarchive:
    src: "{{ binaries_upload_dir }}/{{ ranger_kafka_dist_file }}"
    dest: "{{ kafka_root_dir }}"
    owner: root
    group: root
    mode: "755"
    remote_src: yes
    creates: "{{ kafka_root_dir }}/{{ ranger_kafka_release }}"

- name: Ensure right permissions on ranger libs
  ansible.builtin.file:
    path: "{{ kafka_root_dir }}/{{ ranger_kafka_release }}"
    owner: root
    group: root
    mode: "755"
    recurse: true
    state: directory

- name: Create symbolic link to Ranger installation
  ansible.builtin.file:
    src: "{{ kafka_root_dir }}/{{ ranger_kafka_release }}"
    dest: "{{ ranger_kafka_install_dir }}"
    state: link
