# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Template Airflow worker service file
  ansible.builtin.template:
    src: airflow-worker.service.j2
    dest: /usr/lib/systemd/system/airflow-worker.service
