# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: "Clean-up firewall {{ firewall_service }} rules"
  include_role:
    name: "tosit.tdp_extra.firewall.{{ firewall_service }}"
    tasks_from: clean-up
