# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart Jupyterhub Server
  service:
    name: jupyterhub
    state: restarted
    enabled: "{{ jupyterhub_start_on_boot }}"
