# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Copy TLS key pair to jupyterhub folder
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: root
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - src: "{{ certificates_public_key }}"
      dest: "{{ jupyterhub_public_key }}"
      owner: root
      mode: "0644"
    - src: "{{ certificates_private_key }}"
      dest: "{{ jupyterhub_private_key }}"
      owner: "{{ jupyterhub_user }}"
      mode: "0440"
