# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop Jupyterhub Server
  ansible.builtin.service:
    name: jupyterhub
    state: stopped
    enabled: "{{ jupyterhub_start_on_boot }}"
