---
- name: Airflow | Upload airflow DAGs templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ airflow_dag_dir }}/{{ item | basename | splitext | first }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  with_fileglob: "{{role_path}}/templates/dags/*.j2"
  ignore_errors: true