---
- name: Change ownership and permissions of Airflow logs and SSL keys
  become: yes
  become_user: root
  file:
    path: "{{ item.path }}"
    owner: airflow
    group: airflow
    mode: "{{ item.mode }}"
  with_items:
    - { path: '/var/log/airflow', mode: '755' }
    - { path: '/etc/ssl/certs/{{ ansible_fqdn }}.key', mode: '755' }
    - { path: '/etc/ssl/certs/{{ ansible_fqdn }}.pem', mode: '755' }
