---
- name: Airflow | Ensure kerberos common installation steps are performed
  import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: install

- name: Airflow | Ensure airflow airflow's principal and keytab exist
  import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: create_principal_keytab
  vars:
    principal: airflow/{{ ansible_fqdn }}
    keytab: "{{ airflow_kerberos.keytab }}"
    user: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: "0600"
  when: krb_create_principals_keytabs

- name: Airflow | Ensure airflow's keytab is working
  import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: check_secure_keytab
  vars:
    principal: airflow/{{ ansible_fqdn }}
    keytab: "{{ airflow_kerberos.keytab }}"
    user: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: "0600"
  when: not krb_create_principals_keytabs