# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Copy TLS keys and ca certs to airflow folder
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - src: "{{ certificates_public_key }}"
      dest: "{{ airflow_public_key }}"
      owner: root
      group: root
      mode: "0644"
    - src: "{{ certificates_private_key }}"
      dest: "{{ airflow_private_key }}"
      owner: "{{ airflow_user }}"
      group: "{{ airflow_group }}"
      mode: "0440"
    - src: "{{ certificates_ca }}"
      dest: "{{ ca_certificate_file }}"
      owner: root
      group: root
      mode: "0644"
