# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
# Author: Pierre Marty <pmarty@linagora.com>
# Date: 2022-06-07

---
nifi_name: nifi
nifi_version: 1.16.1
nifi_release: "{{ nifi_name }}-{{ nifi_version }}-bin"
nifi_dist_file: "{{ nifi_release }}.tar.gz"

nifi_user: nifi

nifi_root_dir: /opt/tdp
nifi_install_dir: "{{ nifi_root_dir }}/{{ nifi_name }}-{{ nifi_version }}"
