# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_role:
    name: tosit.tdp_extra.kafka.common
    tasks_from: install

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ kafka_broker_conf_dir }}"
    state: directory
    group: "{{ kafka_group }}"
    owner: "{{ kafka_user }}"
    mode: "755"

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ kafka_group }}"
    owner: "{{ kafka_user }}"
    mode: "750"
  loop: "{{ kafka_data_dirs.split(',')  }}"

- name: Template Kafka Broker service file
  ansible.builtin.template:
    src: kafka-broker.service.j2
    dest: /usr/lib/systemd/system/kafka-broker.service
    owner: root
    group: root
    mode: "644"
