---
- name: Download user ssh keys to control node 
  fetch:
    src: "{{ key_path }}"
    dest: "{{ control_node_ssh_dir }}"
    flat: yes
  loop:
    -  "{{ remote_ssh_private_key_path }}"
    -  "{{ remote_ssh_public_key_path }}"
  loop_control:
    loop_var: key_path
