---
size: 2048
type: rsa
comment: "{{ owner }}@{{ inventory_hostname }}"
owner: "{{ owner }}"
group: "{{ owner }}"
passphrase: ""

ssh_key_name: "id_{{ type }}_{{ owner }}_{{ inventory_hostname }}"
remote_ssh_dir: "/home/{{ owner }}/.ssh"
remote_ssh_public_key_path: "{{ remote_ssh_dir }}/{{ ssh_key_name }}.pub"
remote_authorized_keys_path: "{{ remote_ssh_dir }}authorized_keys"
remote_ssh_private_key_path: "{{ remote_ssh_dir }}/{{ ssh_key_name }}"

control_node_ssh_dir: files/ssh/
control_node_ssh_public_key_path: "{{ control_node_ssh_dir }}{{ ssh_key_name }}.pub"
control_node_ssh_private_key_path: "{{ control_node_ssh_dir }}{{ ssh_key_name }}"
