# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: "Airflow cluster policies"
  hosts: airflow_scheduler
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow_scheduler
    - name: "Airflow cluster policies"
      ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.utils
        tasks_from: cluster_policies
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
