---
- name: "Add Airflow roles"
  hosts: airflow_webserver
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow_webserver
    - name: "Add Airflow roles"
      import_role:
        name: tosit.tdp_extra.airflow.utils
        tasks_from: roles
    - meta: clear_facts # noqa unnamed-task

