# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: "Add Airflow roles"
  hosts: airflow_webserver
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow_webserver
    - name: "Add Airflow roles"
      ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.utils
        tasks_from: roles
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
