# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: "Airflow dags example"
  hosts: airflow
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow
    - name: "Airflow dags example"
      ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.utils
        tasks_from: dags_example
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
