---
- name: Set root password to Vagrant
  user:
    name: root
    password: '{{ "vagrant" | password_hash("sha512", "salt123") }}'

- name: Install common packages
  yum:
    name:
      - vim
      - java-1.8.0-openjdk
      - wget
      - curl
      - unzip
      - nc
      - expect
      # Installing python2-setuptools required by the Ansible pip module
      - python2-setuptools
      - python3
      - python3-pip
      - python3-setuptools
    state: present

- name: Set JAVA_HOME
  lineinfile:
    path: /etc/environment
    regexp: "^JAVA_HOME="
    line: JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk

- name: Upgrade pip3
  pip:
    name:
      - pip
    state: latest
    executable: pip3

- name: Install numpy, pandas and pyarrow
  pip:
    name:
      - numpy~=1.19
      - pandas~=1.0
      - pyarrow~=4.0
      - py4j~=0.10.9
    state: latest
    executable: pip3
