---
- name: "Ranger: get policy list"
  uri:
    url: "{{ ranger_kafka_install_properties.POLICY_MGR_URL }}/service/public/v2/api/policy"
    headers:
      Accept: application/json
    url_username: "{{ ranger_admin_user }}"
    url_password: "{{ ranger_admin_password }}"
    force_basic_auth: yes
    return_content: yes
  register: jsoncontent

- name: Get policy ids
  vars:
    kafka_policy_query: "[? name == '{{ item.name }}'].id"
  set_fact:
    kafka_policy_id: "{{ jsoncontent.json | community.general.json_query(kafka_policy_query) }}"

- name: Create Kafka policy for user
  uri:
    url: "{{ ranger_kafka_install_properties.POLICY_MGR_URL }}/service/public/v2/api/policy"
    headers:
      Accept: application/json
    body: "{{ item | to_json }}"
    body_format: json
    url_username: "{{ ranger_admin_user }}"
    url_password: "{{ ranger_admin_password }}"
    force_basic_auth: yes
    method: POST
  when: not kafka_policy_id
