---
- name: Ensure common airflow installation tasks are performed
  import_role:
    name: tosit.tdp_extra.airflow.common
    tasks_from: install

- name: Pip install flower 
  pip:
    name: "flower"
    executable: pip3
    extra_args: --constraint /tmp/constraints-3.6.txt

