---
- name: Backup configuration
  ansible.builtin.copy:
    src: "{{ livy_server_conf_dir }}/"
    dest: "{{ livy_server_conf_dir }}.{{ ansible_date_time.epoch }}"
    group: "{{ hadoop_group }}"
    owner: "{{ livy_user }}"
    mode: "755"
    remote_src: yes
  tags: ['backup', 'never']

- name: Template livy-env.sh
  ansible.builtin.template:
    src: livy-env.sh.j2
    dest: "{{ livy_server_conf_dir }}/livy-env.sh"
    owner: root
    group: root
    mode: "644"

- name: Template livy-client.conf
  ansible.builtin.template:
    src: livy-client.conf.j2
    dest: "{{ livy_server_conf_dir }}/livy-client.conf"
    owner: root
    group: root
    mode: "644"

- name: Template livy.conf
  ansible.builtin.template:
    src: livy.conf.j2
    dest: "{{ livy_server_conf_dir }}/livy.conf"
    owner: root
    group: root
    mode: "644"

- name: Template log4j.properties
  ansible.builtin.template:
    src: log4j.properties.j2
    dest: "{{ livy_server_conf_dir }}/log4j.properties"
    owner: root
    group: root
    mode: "644"
