---
- ansible.builtin.include_role:
    name: tosit.tdp.utils.ssl_tls
    tasks_from: create_keystore
  vars:
    keystore_location: "{{ livy_keystore_location }}"
    keystore_password: "{{ livy_keystore_password }}"
