# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure common kerberos installation steps are performed
  ansible.builtin.import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: install

- name: Ensure jupyterhub principal and keytab exist
  ansible.builtin.import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: create_principal_keytab
  vars:
    principal: "{{ jupyterhub_principal }}"
    keytab: "jupyterhub.service.keytab"
    user: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: "0600"
  when: krb_create_principals_keytabs

- name: Ensure jupyterhub keytabs works
  ansible.builtin.import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: check_secure_keytab
  vars:
    principal: "{{ jupyterhub_principal }}"
    keytab: "jupyterhub.service.keytab"
    user: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: "0600"
  when: not krb_create_principals_keytabs
