# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Backup configuration
  ansible.builtin.copy:
    src: "{{ kafka_client_conf_dir }}/"
    dest: "{{ kafka_client_conf_dir }}.{{ ansible_date_time.epoch }}"
    owner: root
    group: root
    mode: "755"
    remote_src: yes
  tags:
    - backup

- name: Template client.properties
  ansible.builtin.template:
    src: client.properties.j2
    dest: "{{ kafka_client_conf_dir }}/client.properties"
    owner: root
    group: root
    mode: "644"

- name: Template producer.properties
  ansible.builtin.template:
    src: producer.properties.j2
    dest: "{{ kafka_client_conf_dir }}/producer.properties"
    owner: root
    group: root
    mode: "644"

- name: Template consumer.properties
  ansible.builtin.template:
    src: consumer.properties.j2
    dest: "{{ kafka_client_conf_dir }}/consumer.properties"
    owner: root
    group: root
    mode: "644"

- name: Template Kafka commands
  ansible.builtin.template:
    src: kafka-command.sh.j2
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: "755"
  loop:
    - kafka-acls.sh
    - kafka-broker-api-versions.sh
    - kafka-configs.sh
    - kafka-console-consumer.sh
    - kafka-console-producer.sh
    - kafka-consumer-groups.sh
    - kafka-consumer-perf-test.sh
    - kafka-delegation-tokens.sh
    - kafka-delete-records.sh
    - kafka-features.sh
    - kafka-get-offsets.sh
    - kafka-log-dirs.sh
    - kafka-reassign-partitions.sh
    - kafka-topics.sh
