---
- import_tasks: airflow.yaml

- import_tasks: webserver.yaml
  when: "'airflow_webserver' in group_names"

- import_tasks: scheduler.yaml
  when: "'airflow_webserver' in group_names"

- import_tasks: executor.yaml
  when: "'airflow_executor' in group_names"
