---
- name: Airflow Database Init
  shell: airflow db init
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"

- name: Create Airflow admin user
  shell: |
    airflow users create \
      --username {{ airflow_admin_user }} \
      --password {{ airflow_admin_pass }} \
      --role Admin \
      --firstname admin \
      --lastname admin \
      --email admin@tdp
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"

- name: Template webserver_config.py file
  template:
    src: webserver_config.py.j2
    dest: "{{ airflow_install_dir }}/webserver_config.py"

- name: Template Airflow webserver service file
  template:
    src: airflow-webserver.service.j2
    dest: /usr/lib/systemd/system/airflow-webserver.service