# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../firewall_generic_config.yml
- ansible.builtin.import_playbook: ../firewall_generic_start.yml
# firewall_install
# firewall_config
# firewall_start
# firewall_init
