# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../hue_server_install.yml
- ansible.builtin.import_playbook: ../hue_kerberos_install.yml
- ansible.builtin.import_playbook: ../hue_ssl-tls_install.yml
# hue_install
- ansible.builtin.import_playbook: ../hue_server_config.yml
# hue_config
- ansible.builtin.import_playbook: ../hue_server_start.yml
# hue_server_init
# hue_start
# hue_init
