# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../jupyter_hub_install.yml
- ansible.builtin.import_playbook: ../jupyter_kerberos_install.yml
- ansible.builtin.import_playbook: ../jupyter_lab_install.yml
- ansible.builtin.import_playbook: ../jupyter_lab_config.yml
- ansible.builtin.import_playbook: ../jupyter_ssl-tls_install.yml
- ansible.builtin.import_playbook: ../jupyter_hub_config.yml
- ansible.builtin.import_playbook: ../jupyter_hub_start.yml
# jupyter_install
# jupyter_config
# jupyter_start
# jupyter_init
