# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_playbook: ../jupyterhub_server_install.yml
# jupyterhub_install
- import_playbook: ../jupyterhub_kerberos_install.yml
- import_playbook: ../jupyterhub_ssl-tls_install.yml
- import_playbook: ../jupyterhub_server_config.yml
# jupyterhub_config
- import_playbook: ../jupyterhub_server_start.yml
# jupyterhub_start
- import_playbook: ../jupyterhub_server_hdfs-init.yml
- import_playbook: ../jupyterhub_server_init.yml
# jupyterhub_init
