# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../kafka_broker_install.yml
- ansible.builtin.import_playbook: ../kafka_client_install.yml
- ansible.builtin.import_playbook: ../kafka_jmx-exporter_config.yml
- ansible.builtin.import_playbook: ../kafka_kerberos_install.yml
- ansible.builtin.import_playbook: ../kafka_client_config.yml
- ansible.builtin.import_playbook: ../kafka_ranger_install.yml
- ansible.builtin.import_playbook: ../kafka_ssl-tls_install.yml
# kafka_install
- ansible.builtin.import_playbook: ../kafka_broker_config.yml
- ansible.builtin.import_playbook: ../kafka_ranger_config.yml
# kafka_config
- ansible.builtin.import_playbook: ../kafka_ranger_init.yml
- ansible.builtin.import_playbook: ../kafka_broker_start.yml
# kafka_start
# kafka_init
