# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../zookeeper-kafka_client_install.yml
- ansible.builtin.import_playbook: ../zookeeper-kafka_jmx-exporter_config.yml
- ansible.builtin.import_playbook: ../zookeeper-kafka_server_install.yml
- ansible.builtin.import_playbook: ../zookeeper-kafka_kerberos_install.yml
- ansible.builtin.import_playbook: ../zookeeper-kafka_client_config.yml
# zookeeper-kafka_install
- ansible.builtin.import_playbook: ../zookeeper-kafka_server_config.yml
# zookeeper-kafka_config
- ansible.builtin.import_playbook: ../zookeeper-kafka_server_start.yml
# zookeeper-kafka_server_init
# zookeeper-kafka_start
# zookeeper-kafka_init
