---
- name: "Kerberos Airflow"
  hosts: airflow_worker_edge
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow
    - name: "Kerberos Airflow"
      ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.worker_edge
        tasks_from: kerberos
    - ansible.builtin.meta: clear_facts # noqa unnamed-task

