# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: "Config Airflow"
  hosts: airflow
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow
    - name: "Config Airflow"
      ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.common
        tasks_from: config
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
