---
- name: "Config Airflow"
  hosts: airflow
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow
    - name: "Config Airflow"
      import_role:
        name: tosit.tdp_extra.airflow.common
        tasks_from: config
    - meta: clear_facts # noqa unnamed-task
