# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: "Start Airflow Scheduler"
  hosts: airflow_scheduler
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow_scheduler
    - ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.scheduler
        tasks_from: start
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
