---
- name: "Install Airflow Executor"
  hosts: airflow_executor
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow_executor
    - import_role:
        name: tosit.tdp_extra.airflow.executor
        tasks_from: install
    - meta: clear_facts # noqa unnamed-task
