# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: SSL-TLS Airflow Install
  hosts: airflow
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow
    - name: Install Airflow SSL-TLS
      ansible.builtin.import_role:
        name: tosit.tdp_extra.airflow.common
        tasks_from: ssl-tls
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
