# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Kerberos Hue Server install
  hosts: hue_server
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: hue_kerberos
    - name: Install Hue Server Kerberos
      import_role:
        name: tosit.tdp_extra.hue.server
        tasks_from: kerberos
    - meta: clear_facts # noqa unnamed-task
