# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure Hue Server
  hosts: hue_server
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: livy-spark3_server
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: hue_server
    - name: Configure Hue Server
      ansible.builtin.import_role:
        name: tosit.tdp_extra.hue.server
        tasks_from: config
    - ansible.builtin.meta: clear_facts # noqa unnamed-task

- name: Configure Hive for Hue Server
  hosts: hue_server
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: hive_hue
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: hue_server
    - name: Configure Hive for Hue Server
      ansible.builtin.import_role:
        name: tosit.tdp_extra.hue.server
        tasks_from: config_hive
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
