---
- hosts: hue_server
  become: yes
  tasks:
    - tosit.tdp.resolve:
        node_name: hue_server
    - name: Get active namenode adress
      shell: |
        kinit -kt /etc/security/keytabs/nn.service.keytab nn/{{ item.fqdn }}@{{ realm_name }}
        hdfs haadmin -getAllServiceState | awk ' {if ($NF == "active") print $1}'
      register: webhdfs_endpoint_result
      delegate_to: "{{ item.ansible_host }}"
      with_items:
        - fqdn: "{{ groups['hdfs_nn'][0] | tosit.tdp.access_fqdn(hostvars) }}"
          ansible_host: "{{ groups['hdfs_nn'][0] }}"
    - name: Get active resource manager address
      shell: |
        kinit -kt /etc/security/keytabs/rm.service.keytab rm/{{ item.fqdn }}@{{ realm_name }}
        yarn rmadmin -getAllServiceState | awk ' {if ($NF == "active") print $1}'
      register: yarn_active_rm_result
      delegate_to: "{{ item.ansible_host }}"
      with_items:
        - fqdn: "{{ groups['yarn_rm'][0] | tosit.tdp.access_fqdn(hostvars) }}"
          ansible_host: "{{ groups['yarn_rm'][0] }}"
    - name: "Get {{ hue_user }} uid"
      shell: cat /etc/passwd | grep "{{ hue_user }}:" | awk -F ":" '{print $3}'
      register: hue_user_id_output
    - tosit.tdp.resolve:
        node_name: hue_server
    - name: Update hue.ini
      vars:
        hue_user_id: "{{ hue_user_id_output.stdout | trim }}"
        webhdfs_endpoint: "{{ webhdfs_endpoint_result.results[0].stdout }}"
        yarn_active_rm: "{{ yarn_active_rm_result.results[0].stdout }}"
      include_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp-extra/roles/hue
        tasks_from: template-hue.ini.yml
    - name: Restart hue
      service:
        name: hue.service
        state: restarted

- hosts: hbase_master
  become: yes
  tasks:
    - name: restart hbase-master.service
      service:
        name: hbase-master.service
        state: restarted

- hosts: hbase_rs
  become: yes
  tasks:
    - name: restart hbase-regionserver.service
      service:
        name: hbase-regionserver.service
        state: restarted

- hosts: phoenix_queryserver_daemon
  become: yes
  tasks:
    - name: restart phoenix_queryserver_daemon
      service:
        name: phoenix-queryserver.service
        state: restarted
