# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart Hue Server
  hosts: hue_server
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: hue_server
    - name: Restart Hue Server
      import_role:
        name: tosit.tdp_extra.hue.server
        tasks_from: restart
    - meta: clear_facts # noqa unnamed-task
