---
- hosts: ranger_admin[0]
  become: yes
  tasks:
    - tosit.tdp.resolve:
        node_name: hue_service

    - name: Install hue
      include_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp-extra/roles/hue
        tasks_from: sync-user-to-ranger.yml
