---
- hosts: hue_server
  become: yes
  tasks:
    - tosit.tdp.resolve:
        node_name: hue_server
    - name: Install hue
      include_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp/roles/hue
        tasks_from: install.yml
