# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: HDFS Init Jupyterhub Server
  hosts: jupyterhub_edge
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyterhub_server
    - name: Initialize Jupyterhub Server HDFS
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyterhub.server
        tasks_from: hdfs-init
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
