# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure Jupyterlab
  hosts: jupyter_lab
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyter_lab
    - name: Configure Jupyterlab
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyter.lab
        tasks_from: config
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
