# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart Jupyterhub
  hosts: jupyter_hub
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyter_hub
    - name: Restart Jupyterhub
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyter.hub
        tasks_from: restart
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
