# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Kerberos Jupyterhub install
  hosts: jupyter_hub
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyter_kerberos
    - name: Install Jupyterhub Kerberos
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyter.hub
        tasks_from: kerberos
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
