# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure Jupyterhub
  hosts: jupyter_hub
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyter_hub
    - name: Configure Jupyterhub
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyter.hub
        tasks_from: config
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
