# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Init Jupyterhub Server
  hosts: jupyterhub_server
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyterhub_server
    - name: Initialize Jupyterhub Server
      import_role:
        name: tosit.tdp_extra.jupyterhub.server
        tasks_from: init
    - meta: clear_facts # noqa unnamed-task
