# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Install Jupyterlab
  hosts: yarn_nm
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyter_lab
    - name: Install Jupyterlab
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyter.lab
        tasks_from: install
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
