# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Config jmx-exporter for Kafka Broker
  hosts: kafka_broker
  tasks:
    - tosit.tdp.resolve:
        node_name: kafka_jmx-exporter
    - ansible.builtin.import_role:
        name: tosit.tdp_extra.kafka.broker
        tasks_from: jmx-exporter
    - ansible.builtin.meta: clear_facts
