# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Kafka Ranger plugin config
  hosts: kafka_broker
  tasks:
    - tosit.tdp.resolve:
        node_name: kafka_ranger
    - ansible.builtin.import_role:
        name: tosit.tdp_extra.kafka.ranger
        tasks_from: config
    - ansible.builtin.meta: clear_facts
