---
- name: Kerberos Livy Server Install
  hosts: livy_server
  strategy: linear
  tasks:
    - tosit.tdp.resolve:
        node_name: livy_server
    - import_role:
        name: tosit.tdp_extra.livy.server
        tasks_from: kerberos
    - meta: clear_facts
