---
- import_playbook: livyspark3_server_install.yml
- import_playbook: livyspark3_kerberos_install.yml
- import_playbook: livyspark3_ssl-tls_install.yml
- import_playbook: livyspark3_server_config.yml
- import_playbook: livyspark3_server_start.yml
