---
- name: Livy Server Stop
  hosts: livyspark3_server
  tasks:
    - tosit.tdp.resolve:
        node_name: livyspark3_server
    - import_role:
        name: tosit.tdp_extra.livy.server
        tasks_from: stop
    - meta: clear_facts
