---
- name: Livy Server Config
  hosts: livy_spark3_server
  tasks:
    - tosit.tdp.resolve:
        node_name: livy-spark3_server
    - ansible.builtin.import_role:
        name: tosit.tdp_extra.livy.server
        tasks_from: config
    - ansible.builtin.meta: clear_facts
