# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Zookeeper for Kafka service check
  hosts: zk_kafka_client
  tasks:
    - tosit.tdp.resolve:
        node_name: zookeeper-kafka
    - ansible.builtin.import_role:
        name: tosit.tdp.zookeeper.check
    - ansible.builtin.meta: clear_facts
