# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Zookeeper Server for Kafka stop
  hosts: zk_kafka
  tasks:
    - tosit.tdp.resolve:
        node_name: zookeeper-kafka_server
    - ansible.builtin.import_role:
        name: tosit.tdp.zookeeper.server
        tasks_from: stop
    - ansible.builtin.meta: clear_facts
