---
- name: Trust connections from the ansible host (add to pg_hba.conf)
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host all all 192.168.32.1/32 md5"

- name: Open listen addresses
  become_user: postgres
  shell: sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'"/ /var/lib/pgsql/data/postgresql.conf
  tags: oip

- name: Restart postgresql service
  become: yes
  service:
    name: postgresql
    state: restarted

- name: Give postgres db user a password
  become_user: postgres
  shell: psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres';"
  tags: pgpw
