---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml
- include_tasks: service.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml

# Trust connections from postgresql_client
- import_tasks: trust-clients.yml

# Configure for TDP-getting-started use
- import_tasks: configure-for-tdp-getting-started.yml
  when: config_tdp_getting_started
